tags:
  [
    {
      frame: "tag_1",
      id: 1,
      corners: [
        [-0.09, 0.09, 0.0],
        [0.09, 0.09, 0.0],
        [0.09, -0.09, 0.0]
      ]
    },
    {
      frame: "tag_2",
      id: 2,
      corners: [
        [-0.09, 0.09, 0.0],
        [0.09, 0.09, 0.0],
        [0.09, -0.09, 0.0]
      ]
    },
    {
      frame: "tag_3",
      id: 3,
      corners: [
        [-0.09, 0.09, 0.0],
        [0.09, 0.09, 0.0],
        [0.09, -0.09, 0.0]
      ]
    },
    {
      frame: "tag_4",
      id: 4,
      corners: [
        [-0.09, 0.09, 0.0],
        [0.09, 0.09, 0.0],
        [0.09, -0.09, 0.0]
      ]
    },
    {
      frame: "tag_5",
      id: 5,
      corners: [
        [-0.09, 0.09, 0.0],
        [0.09, 0.09, 0.0],
        [0.09, -0.09, 0.0]
      ]
    },
    {
      frame: "tag_6",
      id: 6,
      corners: [
        [-0.09, 0.09, 0.0],
        [0.09, 0.09, 0.0],
        [0.09, -0.09, 0.0]
      ]
    },
    {
      frame: "tag_7",
      id: 7,
      corners: [
        [-0.09, 0.09, 0.0],
        [0.09, 0.09, 0.0],
        [0.09, -0.09, 0.0]
      ]
    },
    {
      frame: "tag_8",
      id: 8,
      corners: [
        [-0.09, 0.09, 0.0],
        [0.09, 0.09, 0.0],
        [0.09, -0.09, 0.0]
      ]
    },
    {
      frame: "tag_9",
      id: 9,
      corners: [
        [-0.09, 0.09, 0.0],
        [0.09, 0.09, 0.0],
        [0.09, -0.09, 0.0]
      ]
    },
    {
      frame: "tag_10",
      id: 10,
      corners: [
        [-0.09, 0.09, 0.0],
        [0.09, 0.09, 0.0],
        [0.09, -0.09, 0.0]
      ]
    },
    {
      frame: "tag_11",
      id: 11,
      corners: [
        [-0.09, 0.09, 0.0],
        [0.09, 0.09, 0.0],
        [0.09, -0.09, 0.0]
      ]
    },
    {
      frame: "tag_12",
      id: 12,
      corners: [
        [-0.09, 0.09, 0.0],
        [0.09, 0.09, 0.0],
        [0.09, -0.09, 0.0]
      ]
    },
    {
      frame: "tag_13",
      id: 13,
      corners: [
        [-0.09, 0.09, 0.0],
        [0.09, 0.09, 0.0],
        [0.09, -0.09, 0.0]
      ]
    },
    {
      frame: "tag_14",
      id: 14,
      corners: [
        [-0.09, 0.09, 0.0],
        [0.09, 0.09, 0.0],
        [0.09, -0.09, 0.0]
      ]
    },
    {
      frame: "tag_15",
      id: 15,
      corners: [
        [-0.09, 0.09, 0.0],
        [0.09, 0.09, 0.0],
        [0.09, -0.09, 0.0]
      ]
    },
    {
      frame: "tag_16",
      id: 16,
      corners: [
        [-0.09, 0.09, 0.0],
        [0.09, 0.09, 0.0],
        [0.09, -0.09, 0.0]
      ]
    },
    {
      frame: "tag_17",
      id: 17,
      corners: [
        [-0.09, 0.09, 0.0],
        [0.09, 0.09, 0.0],
        [0.09, -0.09, 0.0]
      ]
    },
    {
      frame: "tag_18",
      id: 18,
      corners: [
        [-0.09, 0.09, 0.0],
        [0.09, 0.09, 0.0],
        [0.09, -0.09, 0.0]
      ]
    },
    {
      frame: "tag_19",
      id: 19,
      corners: [
        [-0.09, 0.09, 0.0],
        [0.09, 0.09, 0.0],
        [0.09, -0.09, 0.0]
      ]
    },
    {
      frame: "tag_20",
      id: 20,
      corners: [
        [-0.09, 0.09, 0.0],
        [0.09, 0.09, 0.0],
        [0.09, -0.09, 0.0]
      ]
    }
  ]

# Marker corner order:
# 1          2
#  HD########
#  #ID#  ####
#  ##  ##  ##
#  ####  ####
#  ##########
# 4          3

    